# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Über mich
    url: about/
    weight: 20
  - name: Impressum/Datenschutz
    identifier: impressum-datenschutz
    weight: 30
  - name: Impressum
    parent: impressum-datenschutz
    url: impressum/
    weight: 10
  - name: Datenschutzerklärung
    parent: impressum-datenschutz
    url: datenschutz/
    weight: 31
  # - name: Posts
  #   url: posts/
  #   weight: 15
  #   view: compact
